export const QUERY_KEY = {
  ME: '@me',
  LOGIN: 'login',
  LOGOUT: 'logout',
  REGISTER: 'register',
  SEND_MESSAGE_VERIFY_EMAIL: 'send_message_verify_email',
  VERIFY_EMAIL: 'verify_email',
  SEND_MESSAGE_RESET_PASSWORD_EMAIL: 'send_message_reset_password_email',
  RESET_PASSWORD: 'reset_password',
  PATCH_USER: 'patch_user',
  PATCH_AVATAR: 'patch_avatar',
  USERS: 'users',
  USER_BY_ID: 'user_by_id',
  ADMIN_UPDATE_USER: 'admin_update_user',
  ADMIN_UPDATE_ROLE: 'admin_update_role',
  ADMIN_DELETE_USER: 'admin_delete_user',
  ADMIN_UPDATE_SHOP: 'admin_update_shop',
  ADMIN_DELETE_SHOP: 'admin_delete_shop',
  ADMIN_DELETE_PRODUCT: 'admin_delete_product',

  CREATE_SHOP: 'create_shop',
  PATCH_SHOP: 'patch_shop',
  DELETE_SHOP: 'delete_shop',
  ME_SELECTED_SHOP_ID: 'me_selected_shop_id',
  SHOP_UPLOAD_LOGO: 'shop_upload_logo',
  GET_ALL_SHOPS: 'get_all_shops',
  ME_SHOPS: 'me_shops',
  GET_SHOP_BY_ID: 'shop',
  SHOP_CATEGORIES: 'shop_categories',
  SHOP_COLORS: 'shop_colors',
  SHOP_PRODUCTS: 'shop_products',

  CREATE_CATEGORY: 'create_category',
  GET_ALL_CATEGORY: 'get_all_category',
  DELETE_CATEGORY: 'delete_category',

  CREATE_COLOR: 'create_color',
  GET_ALL_COLORS: 'get_all_colors',
  DELETE_COLOR: 'delete_color',

  CREATE_PRODUCT: 'create_product',
  UPDATE_PRODUCT: 'update_product',
  GET_ALL_PRODUCTS: 'all_products',
  GET_ALL_PRODUCT_WITH_FILTERS: 'all_product_with_filters',
  GET_PRODUCT_BY_ID: 'product',
  DELETE_PRODUCT: 'delete_product',

  ADD_PRODUCT_TO_BASKET: 'add_product_to_basket',
  DECREMENT_PRODUCT_QUANTITY_FROM_BASKET:
    'decrement_product_quantity_from_basket',
  DELETE_PRODUCT_FROM_BASKET: 'delete_product_from_basket',
  GET_BASKET_BY_USER_ID: 'get_basket_by_user_id',
  GET_QUANTITY_BY_PRODUCT_ID: 'get_quantity_by_product_id',
  CHANGE_PRODUCT_SELECT: 'change_product_select',
  CHANGE_ALL_PRODUCT_SELECT: 'change_all_product_select',

  ADD_TO_FAVORITES: 'add_to_favorites',
  DELETE_FROM_FAVORITES: 'delete_from_favorites',
  GET_USER_FAVORITES: 'get_user_favorites',

  CREATE_ORDER_FROM_BASKET: 'create_order_from_basket',
  GET_ORDERS: 'get_orders',
  GET_ORDER_BY_ID: 'get_order_by_id',
  PAY_ORDER: 'pay_order',

  CREATE_REVIEW: 'create_review',
  GET_PRODUCT_REVIEWS: 'GET_PRODUCT_REVIEWS',
  GET_SHOP_REVIEWS: 'GET_SHOP_REVIEWS',
} as const
