export const QUERY_KEY = {
  ME: '@me',
  LOGIN: 'login',
  LOGOUT: 'logout',
  REGISTER: 'register',
  SEND_MESSAGE_VERIFY_EMAIL: 'send_message_verify_email',
  VERIFY_EMAIL: 'verify_email',
  SEND_MESSAGE_RESET_PASSWORD_EMAIL: 'send_message_reset_password_email',
  RESET_PASSWORD: 'reset_password',
  PATCH_USER: 'patch_user',
  PATCH_AVATAR: 'patch_avatar',

  CREATE_SHOP: 'create_shop',
  PATCH_SHOP: 'patch_shop',
  ME_SELECTED_SHOP_ID: 'me_selected_shop_id',
  SHOP_UPLOAD_LOGO: 'shop_upload_logo',
  GET_ALL_SHOPS: 'get_all_shops',
  ME_SHOPS: 'me_shops',
  GET_SHOP_BY_ID: 'shop',
  SHOP_CATEGORIES: 'shop_categories',
  SHOP_COLORS: 'shop_colors',
  SHOP_PRODUCTS: 'shop_products',

  CREATE_CATEGORY: 'create_category',
  GET_ALL_CATEGORY: 'get_all_category',
  DELETE_CATEGORY: 'delete_category',

  CREATE_COLOR: 'create_color',
  GET_ALL_COLORS: 'get_all_colors',
  DELETE_COLOR: 'delete_color',

  CREATE_PRODUCT: 'create_product',
  UPDATE_PRODUCT: 'update_product',
  GET_ALL_PRODUCTS: 'all_products',
  GET_ALL_PRODUCT_WITH_FILTERS: 'all_product_with_filters',
  GET_PRODUCT_BY_ID: 'product',
  DELETE_PRODUCT: 'delete_product',
} as const
