/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface apiEndpoints {
  '/auth/register': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Регистрация пользователя */
    post: operations['AuthController_register']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Вход (логин) */
    post: operations['AuthController_login']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Выход (logout) */
    post: operations['AuthController_logout']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/users/profile': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Получить профиль текущего пользователя */
    get: operations['UsersController_findProfile']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/users/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Получить пользователя по id (только для ADMIN) */
    get: operations['UsersController_findById']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    RegisterDto: {
      /**
       * @description Имя пользователя, отображаемое в системе.
       * @example John Doe
       */
      name: string
      /**
       * @description Уникальный email пользователя. Используется для регистрации и входа.
       * @example example@example.com
       */
      email: string
      /**
       * @description Пароль пользователя. Минимальная длина — 6 символов (валидация на бэкенде).
       * @example password123
       */
      password: string
      /**
       * @description Подтверждение пароля. Должно совпадать с полем "password". Проверяется кастомным валидатором IsPasswordsMatchingConstraint.
       * @example password123
       */
      passwordRepeat: string
    }
    LoginDto: {
      /**
       * @description Email пользователя. Используется как логин при авторизации.
       * @example example@example.com
       */
      email: string
      /**
       * @description Пароль пользователя. Минимальная длина — 6 символов (валидация на бэкенде).
       * @example password123
       */
      password: string
      /**
       * @description Код двухфакторной аутентификации. Обязателен только при включённой 2FA.
       * @example 123456
       */
      code?: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type SchemaRegisterDto = components['schemas']['RegisterDto']
export type SchemaLoginDto = components['schemas']['LoginDto']
export type $defs = Record<string, never>
export interface operations {
  AuthController_register: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterDto']
      }
    }
    responses: {
      /** @description Пользователь зарегистрирован */
      201: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Ошибка валидации входных данных. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Пользователь не найден. Пожалуйста проверьте введенные данные */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Пользователь с такой почтой уже существует */
      409: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  AuthController_login: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginDto']
      }
    }
    responses: {
      /** @description Успешный вход. Может вернуть accessToken в body и/или установить cookie */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Ошибка валидации входных данных. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Неверные учетные данные. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  AuthController_logout: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Сессия завершена. Обычно сервер очищает cookie/refresh-token или инвалидирует сессию. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Нет валидной сессии/токена для выхода. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  UsersController_findProfile: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Профиль текущего пользователя. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Не авторизован (нет/невалидный токен). */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  UsersController_findById: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description ID пользователя */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Пользователь найден. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Не авторизован (нет/невалидный токен). */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Недостаточно прав (требуется роль ADMIN). */
      403: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Пользователь с таким id не найден. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
}
